quarkus:
  http:
    port: 1234
    access-log:
      enabled: true
      log-to-file: false
  virtual-threads:
    enabled: true
  hibernate-orm:
    schema-management:
      strategy: update
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  oidc:
    application-type: service
    auth-server-url: http://localhost:8080/realms/metatrack
  minio:
    host: http://localhost
    port: 9000
    secure: false
    access-key: minioadmin
    secret-key: minioadmin
    secure: true
    region: eu-west-1
    force-path-style: true
    bucket-name: metatrack
  smallrye-openapi:
    path: /openapi
    always-include: true
