quarkus:
  http:
    port: 1234
    access-log:
      enabled: true
      log-to-file: false
  virtual-threads:
    enabled: true
  hibernate-orm:
    schema-management:
      strategy: update
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  oidc:
    application-type: service
    auth-server-url: http://localhost:8080/realms/metatrack
  minio:
    host: http://localhost
    port: 9000
    secure: false
    access-key: minioadmin
    secret-key: minioadmin
    bucket-name: metatrack
  smallrye-openapi:
    path: /q/openapi
    always-include: true
    store-schema-directory: src/main/resources/META-INF/resources
  log:
    console:
      json:
        enable: true
        log-format: ECS
    category:
      "io.quarkus.http.access-log":
        level: INFO
