quarkus:
  http:
    port: 1234
    access-log:
      enabled: true
      log-to-file: false
  virtual-threads:
    enabled: true
  hibernate-orm:
    database:
      start-offline: true
    physical-naming-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    db-kind: postgresql
    username: postgres
    jdbc:
      url: jdbc:postgresql://localhost:5432/postgres
  flyway:
    baseline-on-migrate: true
    migrate-at-start: true
  oidc:
    application-type: service
    auth-server-url: http://localhost:8080/realms/metatrack
  minio:
    host: http://localhost
    port: 9000
    access-key: minioadmin
    secret-key: minioadmin
    secure: true
    region: eu-west-1
    force-path-style: true
    bucket-name: metatrack
  smallrye-openapi:
    path: /openapi
    always-include: true
