quarkus:
  http:
    port: 1234
  virtual-threads:
    enabled: true
  hibernate-orm:
    schema-management:
      strategy: drop-and-create
  oidc:
    application-type: service
    auth-server-url: http://localhost:8080/realms/metatrack